name: ${project.name}
main: com.untamedears.JukeAlert.JukeAlert
version: ${project.version}
author: mgrandi
depend: [Citadel, NameLayer, CivModCore]
softdepend: [vanishnopacket, ItemExchange, Mercury]
description: JukeAlert provides an easy-to-use means by which one can record player activity within an 11 block radius. Anything someone does while within eleven blocks of a jukebox you've reinforced will be logged on it, and can be read by looking at the jukebox and typing '/jainfo'.
commands:
  ja:
    description: Opens snitch log GUI
    usage: /ja
  jahelp:
    description: Displays help
    usage: /jahelp
  jainfo:
    description: Display information from a snitch
    usage: /jainfo [<page number> or 'next'] [censor] [action=<action type>] [player=<player name>]
  jalist:
    description: Displays Juke List Information
    usage: /jalist <page number> [groups=<group1>,<group2>,...]
  jalistlong:
    description: Displays Juke List Information with full-length Snitch names
    usage: /jalistlong <page number> [groups=<group1>,<group2>,...]
  jagroup:
    description: Display information from a group
    usage: /jagroup <group> <page>
    permission: jukealert.jagroup
  jaclear:
    description: Clear information from a snitch
    usage: /jaclear
  janame:
    description: Name a snitch
    usage: /janame <name>
  jalookup:
    description: Look up a snitch by its coordinates
    usage: /jalookup <x> <y> <z> [world]
    permission: jukealert.jalookup
  jamute:
    description:  Adds or removes from a snitch notification ignore list.
    usage: /jamute <group>
  jaconfig:
    description: Run-time configuration
    usage: /jaconfig <option> <value>
    permission: jukealert.admin.jaconfig
  jatogglelevers:
    description:  Sets flag that indicates if a juke should trigger a lever.
    usage: /jatogglelevers <0|1>
  jarefuel:
    description: Refuel super snitches
    usage: /jarefuel <'max' | stamina(int)>
    aliases: [jaf, jafuel]
permissions:
  jukealert.admin.jagroup:
    description: Use /jagroup even when not the owner
    default: false
  jukealert.admin.lookupany:
    description: Use /jalookup even when not the owner
    default: false
  jukealert.admin.jaconfig:
    description: Ability to use /jaconfig
    default: false
  jukealert.admin:
    description: Grants permission to JukeAlert admin commands.
    default: op
    children:
      jukealert.admin.jagroup: true
      jukealert.admin.lookupany: true
      jukealert.admin.jaconfig: true
  jukealert.jagroup:
    description: Ability to use /jagroup
    default: op
  jukealert.jalookup:
    description: Ability to use /jalookup
    default: true
  jukealert.vanish:
    description: Ability to avoid snitches.
    default: op
